{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e10c0981",
   "metadata": {},
   "source": [
    "YoloV8\n",
    "- https://docs.ultralytics.com/ko"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "69794ce0",
   "metadata": {},
   "source": [
    "# 1. Yolov8을 위한 패키지 설치 및 import"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a00cb363",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting ultralytics\n",
      "  Downloading ultralytics-8.3.55-py3-none-any.whl (904 kB)\n",
      "     ------------------------------------- 904.3/904.3 kB 14.2 MB/s eta 0:00:00\n",
      "Requirement already satisfied: numpy>=1.23.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (1.23.5)\n",
      "Collecting ultralytics-thop>=2.0.0\n",
      "  Downloading ultralytics_thop-2.0.13-py3-none-any.whl (26 kB)\n",
      "Requirement already satisfied: tqdm>=4.64.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (4.64.1)\n",
      "Requirement already satisfied: opencv-python>=4.6.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (4.10.0.84)\n",
      "Requirement already satisfied: scipy>=1.4.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (1.10.0)\n",
      "Requirement already satisfied: pillow>=7.1.2 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (9.4.0)\n",
      "Requirement already satisfied: pyyaml>=5.3.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (6.0)\n",
      "Requirement already satisfied: torch!=2.4.0,>=1.8.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (1.12.1)\n",
      "Requirement already satisfied: requests>=2.23.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (2.28.1)\n",
      "Requirement already satisfied: pandas>=1.1.4 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (1.5.3)\n",
      "Requirement already satisfied: seaborn>=0.11.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (0.12.2)\n",
      "Requirement already satisfied: psutil in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (5.9.0)\n",
      "Requirement already satisfied: matplotlib>=3.3.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from ultralytics) (3.7.0)\n",
      "Collecting torchvision>=0.9.0\n",
      "  Downloading torchvision-0.20.1-cp310-cp310-win_amd64.whl (1.6 MB)\n",
      "     ---------------------------------------- 1.6/1.6 MB 19.6 MB/s eta 0:00:00\n",
      "Collecting py-cpuinfo\n",
      "  Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (4.25.0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (1.0.5)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (3.0.9)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.4)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (22.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from matplotlib>=3.3.0->ultralytics) (0.11.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from pandas>=1.1.4->ultralytics) (2022.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from requests>=2.23.0->ultralytics) (3.4)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from requests>=2.23.0->ultralytics) (2.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from requests>=2.23.0->ultralytics) (2024.8.30)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from requests>=2.23.0->ultralytics) (1.26.14)\n",
      "Requirement already satisfied: typing_extensions in c:\\users\\4545\\anaconda3\\lib\\site-packages (from torch!=2.4.0,>=1.8.0->ultralytics) (4.12.2)\n",
      "Collecting torch!=2.4.0,>=1.8.0\n",
      "  Downloading torch-2.5.1-cp310-cp310-win_amd64.whl (203.1 MB)\n",
      "     -------------------------------------- 203.1/203.1 MB 6.9 MB/s eta 0:00:00\n",
      "Requirement already satisfied: networkx in c:\\users\\4545\\anaconda3\\lib\\site-packages (from torch!=2.4.0,>=1.8.0->ultralytics) (2.8.4)\n",
      "Requirement already satisfied: filelock in c:\\users\\4545\\anaconda3\\lib\\site-packages (from torch!=2.4.0,>=1.8.0->ultralytics) (3.9.0)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from torch!=2.4.0,>=1.8.0->ultralytics) (3.1.2)\n",
      "Collecting sympy==1.13.1\n",
      "  Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)\n",
      "     ---------------------------------------- 6.2/6.2 MB 26.3 MB/s eta 0:00:00\n",
      "Requirement already satisfied: fsspec in c:\\users\\4545\\anaconda3\\lib\\site-packages (from torch!=2.4.0,>=1.8.0->ultralytics) (2022.11.0)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from sympy==1.13.1->torch!=2.4.0,>=1.8.0->ultralytics) (1.2.1)\n",
      "Requirement already satisfied: colorama in c:\\users\\4545\\anaconda3\\lib\\site-packages (from tqdm>=4.64.0->ultralytics) (0.4.6)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\4545\\anaconda3\\lib\\site-packages (from jinja2->torch!=2.4.0,>=1.8.0->ultralytics) (2.1.1)\n",
      "Installing collected packages: py-cpuinfo, sympy, torch, ultralytics-thop, torchvision, ultralytics\n",
      "  Attempting uninstall: sympy\n",
      "    Found existing installation: sympy 1.11.1\n",
      "    Uninstalling sympy-1.11.1:\n",
      "      Successfully uninstalled sympy-1.11.1\n",
      "  Attempting uninstall: torch\n",
      "    Found existing installation: torch 1.12.1\n",
      "    Uninstalling torch-1.12.1:\n",
      "      Successfully uninstalled torch-1.12.1\n",
      "Successfully installed py-cpuinfo-9.0.0 sympy-1.13.1 torch-2.5.1 torchvision-0.20.1 ultralytics-8.3.55 ultralytics-thop-2.0.13\n"
     ]
    }
   ],
   "source": [
    "! pip install ultralytics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e1b1e42a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name: ultralytics\n",
      "Version: 8.3.55\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 155, in print_results\n",
      "    write_output(\"Summary: %s\", dist.summary)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Summary: %s'\n",
      "Arguments: ('Ultralytics YOLO \\U0001f680 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 156, in print_results\n",
      "    write_output(\"Home-page: %s\", dist.homepage)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Home-page: %s'\n",
      "Arguments: ('',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 157, in print_results\n",
      "    write_output(\"Author: %s\", dist.author)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Author: %s'\n",
      "Arguments: ('',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 158, in print_results\n",
      "    write_output(\"Author-email: %s\", dist.author_email)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Author-email: %s'\n",
      "Arguments: ('Glenn Jocher <glenn.jocher@ultralytics.com>, Jing Qiu <jing.qiu@ultralytics.com>',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 159, in print_results\n",
      "    write_output(\"License: %s\", dist.license)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'License: %s'\n",
      "Arguments: ('AGPL-3.0',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 160, in print_results\n",
      "    write_output(\"Location: %s\", dist.location)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Location: %s'\n",
      "Arguments: ('c:\\\\users\\\\4545\\\\anaconda3\\\\lib\\\\site-packages',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 161, in print_results\n",
      "    write_output(\"Requires: %s\", \", \".join(dist.requires))\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Requires: %s'\n",
      "Arguments: ('matplotlib, numpy, opencv-python, pandas, pillow, psutil, py-cpuinfo, pyyaml, requests, scipy, seaborn, torch, torch, torchvision, tqdm, ultralytics-thop',)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 177, in emit\n",
      "    self.console.print(renderable, overflow=\"ignore\", crop=False, style=style)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1646, in print\n",
      "    with self:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 848, in __exit__\n",
      "    self._exit_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 806, in _exit_buffer\n",
      "    self._check_buffer()\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\console.py\", line 1999, in _check_buffer\n",
      "    legacy_windows_render(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_windows_renderer.py\", line 19, in legacy_windows_render\n",
      "    term.write_text(text)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_vendor\\rich\\_win32_console.py\", line 403, in write_text\n",
      "    self.write(text)\n",
      "UnicodeEncodeError: 'cp949' codec can't encode character '\\U0001f680' in position 26: illegal multibyte sequence\n",
      "Call stack:\n",
      "  File \"C:\\Users\\4545\\anaconda3\\Scripts\\pip-script.py\", line 10, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\main.py\", line 70, in main\n",
      "    return command.main(cmd_args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 101, in main\n",
      "    return self._main(args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 214, in _main\n",
      "    return run(options, args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py\", line 160, in exc_logging_wrapper\n",
      "    status = run_func(*args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 45, in run\n",
      "    if not print_results(\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\commands\\show.py\", line 162, in print_results\n",
      "    write_output(\"Required-by: %s\", \", \".join(dist.required_by))\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\misc.py\", line 336, in write_output\n",
      "    logger.info(msg, *args)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1477, in info\n",
      "    self._log(INFO, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1624, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1634, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 1696, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\logging\\__init__.py\", line 968, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\4545\\anaconda3\\lib\\site-packages\\pip\\_internal\\utils\\logging.py\", line 179, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Required-by: %s'\n",
      "Arguments: ('',)\n"
     ]
    }
   ],
   "source": [
    "! pip show ultralytics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "531d3661",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating new Ultralytics Settings v0.0.6 file  \n",
      "View Ultralytics Settings with 'yolo settings' or at 'C:\\Users\\4545\\AppData\\Roaming\\Ultralytics\\settings.json'\n",
      "Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.\n"
     ]
    }
   ],
   "source": [
    "from ultralytics import YOLO\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "eec39894",
   "metadata": {},
   "source": [
    "# 2. YOLO 인스턴스 생성하여 사물인식 처리"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ef5ff765",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt'...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|█████████████████████████████████████████████████████████████████████████████| 6.25M/6.25M [00:00<00:00, 18.7MB/s]\n"
     ]
    }
   ],
   "source": [
    "model = YOLO('yolov8n.pt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f1a7917b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "image 1/1 D:\\ai\\source\\09_\\data\\mission_impossible_yolo.jpg: 352x640 1 person, 9 cars, 6 motorcycles, 73.1ms\n",
      "Speed: 3.0ms preprocess, 73.1ms inference, 2.0ms postprocess per image at shape (1, 3, 352, 640)\n"
     ]
    }
   ],
   "source": [
    "result = model.predict('data/mission_impossible_yolo.jpg')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8fdc21a3",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[ultralytics.engine.results.Results object with attributes:\n",
       " \n",
       " boxes: ultralytics.engine.results.Boxes object\n",
       " keypoints: None\n",
       " masks: None\n",
       " names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}\n",
       " obb: None\n",
       " orig_img: array([[[107, 133, 147],\n",
       "         [107, 133, 147],\n",
       "         [107, 133, 147],\n",
       "         ...,\n",
       "         [ 65,  98,  77],\n",
       "         [ 67, 100,  79],\n",
       "         [ 64,  95,  74]],\n",
       " \n",
       "        [[113, 139, 153],\n",
       "         [113, 139, 153],\n",
       "         [113, 139, 153],\n",
       "         ...,\n",
       "         [ 64,  97,  76],\n",
       "         [ 66,  99,  78],\n",
       "         [ 64,  95,  74]],\n",
       " \n",
       "        [[124, 150, 164],\n",
       "         [125, 151, 165],\n",
       "         [125, 151, 165],\n",
       "         ...,\n",
       "         [ 64,  97,  76],\n",
       "         [ 67,  98,  77],\n",
       "         [ 69,  97,  77]],\n",
       " \n",
       "        ...,\n",
       " \n",
       "        [[180, 171, 161],\n",
       "         [180, 171, 161],\n",
       "         [180, 171, 161],\n",
       "         ...,\n",
       "         [161, 152, 142],\n",
       "         [163, 154, 144],\n",
       "         [161, 152, 142]],\n",
       " \n",
       "        [[180, 171, 161],\n",
       "         [180, 171, 161],\n",
       "         [180, 171, 161],\n",
       "         ...,\n",
       "         [163, 154, 144],\n",
       "         [165, 156, 146],\n",
       "         [165, 156, 146]],\n",
       " \n",
       "        [[180, 171, 161],\n",
       "         [180, 171, 161],\n",
       "         [180, 171, 161],\n",
       "         ...,\n",
       "         [167, 158, 148],\n",
       "         [169, 160, 150],\n",
       "         [169, 160, 150]]], dtype=uint8)\n",
       " orig_shape: (480, 873)\n",
       " path: 'D:\\\\ai\\\\source\\\\09_이미지처리\\\\data\\\\mission_impossible_yolo.jpg'\n",
       " probs: None\n",
       " save_dir: 'C:\\\\Users\\\\4545\\\\runs\\\\detect\\\\predict'\n",
       " speed: {'preprocess': 2.991914749145508, 'inference': 73.13728332519531, 'postprocess': 1.9943714141845703}]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "result"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "208a90a6",
   "metadata": {},
   "source": [
    "# 3.결과 시각화"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "3e334951",
   "metadata": {},
   "outputs": [],
   "source": [
    "result_image = result[0].plot() # BGR포맷"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "e2c615c9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "cv2.imwrite('data/mission_impossible_yoloresult.jpg', result_image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64343583",
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.imshow(cv2.cvtColor(result_image, cv2.COLOR_BGR2RGB))\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d2243b12",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ccd82182",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a32a486f",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2eef8df7",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9f509d1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24550da8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61ac32c6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5f46d6eb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3383eca",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e8c178f2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "744752de",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "203e88f2",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "af87bab6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a81179f6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "63e27aa6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
